export const ERROR_CODES = Object.freeze({
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  FORBIDDEN: 'FORBIDDEN',
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  UNSUPPORTED_FILE_TYPE: 'UNSUPPORTED_FILE_TYPE',
  MIME_MISMATCH: 'MIME_MISMATCH',
  VIRUS_DETECTED: 'VIRUS_DETECTED',
  DUPLICATE_FILE: 'DUPLICATE_FILE',
  ASSET_IN_USE: 'ASSET_IN_USE',
  STORAGE_PROVIDER_ERROR: 'STORAGE_PROVIDER_ERROR',
  RATE_LIMITED: 'RATE_LIMITED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
});

export default ERROR_CODES;
